// Code generated by qtc from "campaign.html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/campaign.html.qtpl:1
package views

//line views/campaign.html.qtpl:1
import (
	"github.com/etherealmachine/rpg.ai/server/models"
	"github.com/nleeper/goment"
)

//line views/campaign.html.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/campaign.html.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/campaign.html.qtpl:7
type CampaignPage struct {
	*BasePage
	Campaign *models.Campaign
}

//line views/campaign.html.qtpl:13
func (p *CampaignPage) StreamContent(qw422016 *qt422016.Writer) {
//line views/campaign.html.qtpl:13
	qw422016.N().S(`
  <div class="container">
  </div>
`)
//line views/campaign.html.qtpl:16
}

//line views/campaign.html.qtpl:16
func (p *CampaignPage) WriteContent(qq422016 qtio422016.Writer) {
//line views/campaign.html.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/campaign.html.qtpl:16
	p.StreamContent(qw422016)
//line views/campaign.html.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line views/campaign.html.qtpl:16
}

//line views/campaign.html.qtpl:16
func (p *CampaignPage) Content() string {
//line views/campaign.html.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line views/campaign.html.qtpl:16
	p.WriteContent(qb422016)
//line views/campaign.html.qtpl:16
	qs422016 := string(qb422016.B)
//line views/campaign.html.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line views/campaign.html.qtpl:16
	return qs422016
//line views/campaign.html.qtpl:16
}

//line views/campaign.html.qtpl:18
func StreamCampaignCreator(qw422016 *qt422016.Writer, p *BasePage) {
//line views/campaign.html.qtpl:18
	qw422016.N().S(`
  <form action="/campaign/create" method="POST">
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" name="Name" placeholder="Name" />
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" name="Description"></textarea>
    </div>
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/campaign.html.qtpl:28
	qw422016.E().S(p.CsrfToken)
//line views/campaign.html.qtpl:28
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
`)
//line views/campaign.html.qtpl:31
}

//line views/campaign.html.qtpl:31
func WriteCampaignCreator(qq422016 qtio422016.Writer, p *BasePage) {
//line views/campaign.html.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/campaign.html.qtpl:31
	StreamCampaignCreator(qw422016, p)
//line views/campaign.html.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line views/campaign.html.qtpl:31
}

//line views/campaign.html.qtpl:31
func CampaignCreator(p *BasePage) string {
//line views/campaign.html.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line views/campaign.html.qtpl:31
	WriteCampaignCreator(qb422016, p)
//line views/campaign.html.qtpl:31
	qs422016 := string(qb422016.B)
//line views/campaign.html.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line views/campaign.html.qtpl:31
	return qs422016
//line views/campaign.html.qtpl:31
}

//line views/campaign.html.qtpl:33
func StreamCampaignDisplay(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/campaign.html.qtpl:33
	qw422016.N().S(`
  <div class="collapse show campaign-`)
//line views/campaign.html.qtpl:34
	qw422016.E().V(campaign.ID)
//line views/campaign.html.qtpl:34
	qw422016.N().S(`">
    `)
//line views/campaign.html.qtpl:35
	StreamCampaignCard(qw422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:35
	qw422016.N().S(`
    <button
        class="btn btn-secondary"
        type="button"
        data-toggle="collapse"
        data-target=".campaign-`)
//line views/campaign.html.qtpl:40
	qw422016.E().V(campaign.ID)
//line views/campaign.html.qtpl:40
	qw422016.N().S(`">Edit</button>
  </div>
  <div class="collapse campaign-`)
//line views/campaign.html.qtpl:42
	qw422016.E().V(campaign.ID)
//line views/campaign.html.qtpl:42
	qw422016.N().S(`">
    `)
//line views/campaign.html.qtpl:43
	StreamCampaignEditor(qw422016, p, campaign)
//line views/campaign.html.qtpl:43
	qw422016.N().S(`
    <button
        class="btn btn-warning"
        type="button"
        data-toggle="collapse"
        data-target=".campaign-`)
//line views/campaign.html.qtpl:48
	qw422016.E().V(campaign.ID)
//line views/campaign.html.qtpl:48
	qw422016.N().S(`">Cancel</button>
  </div>
`)
//line views/campaign.html.qtpl:50
}

//line views/campaign.html.qtpl:50
func WriteCampaignDisplay(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/campaign.html.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/campaign.html.qtpl:50
	StreamCampaignDisplay(qw422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line views/campaign.html.qtpl:50
}

//line views/campaign.html.qtpl:50
func CampaignDisplay(p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) string {
//line views/campaign.html.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line views/campaign.html.qtpl:50
	WriteCampaignDisplay(qb422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:50
	qs422016 := string(qb422016.B)
//line views/campaign.html.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line views/campaign.html.qtpl:50
	return qs422016
//line views/campaign.html.qtpl:50
}

//line views/campaign.html.qtpl:52
func StreamCampaignCard(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/campaign.html.qtpl:52
	qw422016.N().S(`
  <div class="card">
    <div class="card-body">
      <h5 class="card-title d-flex flex-row justify-content-between">
        <span>`)
//line views/campaign.html.qtpl:56
	qw422016.E().S(campaign.Name)
//line views/campaign.html.qtpl:56
	qw422016.N().S(`</span>
        `)
//line views/campaign.html.qtpl:57
	if g, err := goment.New(campaign.CreatedAt); err == nil {
//line views/campaign.html.qtpl:57
		qw422016.N().S(`
          <span class="text-muted">`)
//line views/campaign.html.qtpl:58
		qw422016.E().S(g.FromNow())
//line views/campaign.html.qtpl:58
		qw422016.N().S(`</span>
        `)
//line views/campaign.html.qtpl:59
	}
//line views/campaign.html.qtpl:59
	qw422016.N().S(`
      </h5>
      <p class="card-text">`)
//line views/campaign.html.qtpl:61
	qw422016.E().S(campaign.Description.String)
//line views/campaign.html.qtpl:61
	qw422016.N().S(`</p>
      <h5>Encounters</h5>
      `)
//line views/campaign.html.qtpl:63
	for _, encounter := range campaign.Encounters {
//line views/campaign.html.qtpl:63
		qw422016.N().S(`
        `)
//line views/campaign.html.qtpl:64
		StreamEncounterDisplay(qw422016, p, campaign, encounter, tilemaps)
//line views/campaign.html.qtpl:64
		qw422016.N().S(`
      `)
//line views/campaign.html.qtpl:65
	}
//line views/campaign.html.qtpl:65
	qw422016.N().S(`
      `)
//line views/campaign.html.qtpl:66
	StreamEncounterCreator(qw422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:66
	qw422016.N().S(`
    </div>
  </div>
`)
//line views/campaign.html.qtpl:69
}

//line views/campaign.html.qtpl:69
func WriteCampaignCard(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/campaign.html.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/campaign.html.qtpl:69
	StreamCampaignCard(qw422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line views/campaign.html.qtpl:69
}

//line views/campaign.html.qtpl:69
func CampaignCard(p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) string {
//line views/campaign.html.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line views/campaign.html.qtpl:69
	WriteCampaignCard(qb422016, p, campaign, tilemaps)
//line views/campaign.html.qtpl:69
	qs422016 := string(qb422016.B)
//line views/campaign.html.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line views/campaign.html.qtpl:69
	return qs422016
//line views/campaign.html.qtpl:69
}

//line views/campaign.html.qtpl:71
func StreamCampaignEditor(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign) {
//line views/campaign.html.qtpl:71
	qw422016.N().S(`
  <form action="/campaign/update" method="POST">
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" name="Name" value="`)
//line views/campaign.html.qtpl:75
	qw422016.E().S(campaign.Name)
//line views/campaign.html.qtpl:75
	qw422016.N().S(`" />
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" name="Description">`)
//line views/campaign.html.qtpl:79
	qw422016.E().S(campaign.Description.String)
//line views/campaign.html.qtpl:79
	qw422016.N().S(`</textarea>
    </div>
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/campaign.html.qtpl:81
	qw422016.E().S(p.CsrfToken)
//line views/campaign.html.qtpl:81
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
  <form action="/campaign/delete" method="POST">
    <input type="hidden" name="ID" value="`)
//line views/campaign.html.qtpl:85
	qw422016.E().V(campaign.ID)
//line views/campaign.html.qtpl:85
	qw422016.N().S(`" />
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/campaign.html.qtpl:86
	qw422016.E().S(p.CsrfToken)
//line views/campaign.html.qtpl:86
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
`)
//line views/campaign.html.qtpl:89
}

//line views/campaign.html.qtpl:89
func WriteCampaignEditor(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign) {
//line views/campaign.html.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/campaign.html.qtpl:89
	StreamCampaignEditor(qw422016, p, campaign)
//line views/campaign.html.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line views/campaign.html.qtpl:89
}

//line views/campaign.html.qtpl:89
func CampaignEditor(p *BasePage, campaign models.FilledCampaign) string {
//line views/campaign.html.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
//line views/campaign.html.qtpl:89
	WriteCampaignEditor(qb422016, p, campaign)
//line views/campaign.html.qtpl:89
	qs422016 := string(qb422016.B)
//line views/campaign.html.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
//line views/campaign.html.qtpl:89
	return qs422016
//line views/campaign.html.qtpl:89
}
