// Code generated by qtc from "encounters.html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/encounters.html.qtpl:1
package views

//line views/encounters.html.qtpl:1
import (
	"github.com/etherealmachine/rpg.ai/server/models"
)

//line views/encounters.html.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/encounters.html.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/encounters.html.qtpl:5
func StreamEncounterDisplay(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:5
	qw422016.N().S(`
  <div class="collapse show encounter-`)
//line views/encounters.html.qtpl:6
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:6
	qw422016.N().S(`">
    `)
//line views/encounters.html.qtpl:7
	StreamEncounterCard(qw422016, p, campaign, encounter)
//line views/encounters.html.qtpl:7
	qw422016.N().S(`
    <button
        class="btn btn-secondary"
        type="button"
        data-toggle="collapse"
        data-target=".encounter-`)
//line views/encounters.html.qtpl:12
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:12
	qw422016.N().S(`">Edit</button>
  </div>
  <div class="collapse encounter-`)
//line views/encounters.html.qtpl:14
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:14
	qw422016.N().S(`">
    `)
//line views/encounters.html.qtpl:15
	StreamEncounterEditor(qw422016, p, campaign, encounter, tilemaps)
//line views/encounters.html.qtpl:15
	qw422016.N().S(`
    <button
        class="btn btn-warning"
        type="button"
        data-toggle="collapse"
        data-target=".encounter-`)
//line views/encounters.html.qtpl:20
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:20
	qw422016.N().S(`">Cancel</button>
  </div>
`)
//line views/encounters.html.qtpl:22
}

//line views/encounters.html.qtpl:22
func WriteEncounterDisplay(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/encounters.html.qtpl:22
	StreamEncounterDisplay(qw422016, p, campaign, encounter, tilemaps)
//line views/encounters.html.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line views/encounters.html.qtpl:22
}

//line views/encounters.html.qtpl:22
func EncounterDisplay(p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) string {
//line views/encounters.html.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line views/encounters.html.qtpl:22
	WriteEncounterDisplay(qb422016, p, campaign, encounter, tilemaps)
//line views/encounters.html.qtpl:22
	qs422016 := string(qb422016.B)
//line views/encounters.html.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line views/encounters.html.qtpl:22
	return qs422016
//line views/encounters.html.qtpl:22
}

//line views/encounters.html.qtpl:24
func StreamEncounterCard(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter) {
//line views/encounters.html.qtpl:24
	qw422016.N().S(`
  <div>
    <h6>`)
//line views/encounters.html.qtpl:26
	qw422016.E().S(encounter.Name)
//line views/encounters.html.qtpl:26
	qw422016.N().S(`</h6>
    <p>`)
//line views/encounters.html.qtpl:27
	qw422016.E().S(encounter.Description.String)
//line views/encounters.html.qtpl:27
	qw422016.N().S(`</p>
    `)
//line views/encounters.html.qtpl:28
	if encounter.Tilemap != nil {
//line views/encounters.html.qtpl:28
		qw422016.N().S(`
      <p>`)
//line views/encounters.html.qtpl:29
		qw422016.E().S(encounter.Tilemap.Name)
//line views/encounters.html.qtpl:29
		qw422016.N().S(`</p>
    `)
//line views/encounters.html.qtpl:30
	}
//line views/encounters.html.qtpl:30
	qw422016.N().S(`
    `)
//line views/encounters.html.qtpl:31
	for _, character := range encounter.Characters {
//line views/encounters.html.qtpl:31
		qw422016.N().S(`
      <p>`)
//line views/encounters.html.qtpl:32
		qw422016.E().S(character.Name)
//line views/encounters.html.qtpl:32
		qw422016.N().S(`</p>
    `)
//line views/encounters.html.qtpl:33
	}
//line views/encounters.html.qtpl:33
	qw422016.N().S(`
  </div>
`)
//line views/encounters.html.qtpl:35
}

//line views/encounters.html.qtpl:35
func WriteEncounterCard(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter) {
//line views/encounters.html.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/encounters.html.qtpl:35
	StreamEncounterCard(qw422016, p, campaign, encounter)
//line views/encounters.html.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line views/encounters.html.qtpl:35
}

//line views/encounters.html.qtpl:35
func EncounterCard(p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter) string {
//line views/encounters.html.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/encounters.html.qtpl:35
	WriteEncounterCard(qb422016, p, campaign, encounter)
//line views/encounters.html.qtpl:35
	qs422016 := string(qb422016.B)
//line views/encounters.html.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/encounters.html.qtpl:35
	return qs422016
//line views/encounters.html.qtpl:35
}

//line views/encounters.html.qtpl:37
func StreamEncounterEditor(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:37
	qw422016.N().S(`
  <form action="/encounter/update" method="POST">
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" name="Name" value="`)
//line views/encounters.html.qtpl:41
	qw422016.E().S(encounter.Name)
//line views/encounters.html.qtpl:41
	qw422016.N().S(`" />
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" name="Description">`)
//line views/encounters.html.qtpl:45
	qw422016.E().S(encounter.Description.String)
//line views/encounters.html.qtpl:45
	qw422016.N().S(`</textarea>
    </div>
    <div class="form-group">
      <label for="tilemap">Tilemap</label>
      <select class="form-control" name="TilemapID">
        `)
//line views/encounters.html.qtpl:50
	for _, tilemap := range tilemaps {
//line views/encounters.html.qtpl:50
		qw422016.N().S(`
          `)
//line views/encounters.html.qtpl:51
		if encounter.TilemapID.Valid && encounter.TilemapID.Int32 == tilemap.ID {
//line views/encounters.html.qtpl:51
			qw422016.N().S(`
            <option value="`)
//line views/encounters.html.qtpl:52
			qw422016.E().V(tilemap.ID)
//line views/encounters.html.qtpl:52
			qw422016.N().S(`" selected>`)
//line views/encounters.html.qtpl:52
			qw422016.E().S(tilemap.Name)
//line views/encounters.html.qtpl:52
			qw422016.N().S(`</option>
          `)
//line views/encounters.html.qtpl:53
		} else {
//line views/encounters.html.qtpl:53
			qw422016.N().S(`
            <option value="`)
//line views/encounters.html.qtpl:54
			qw422016.E().V(tilemap.ID)
//line views/encounters.html.qtpl:54
			qw422016.N().S(`">`)
//line views/encounters.html.qtpl:54
			qw422016.E().S(tilemap.Name)
//line views/encounters.html.qtpl:54
			qw422016.N().S(`</option>
          `)
//line views/encounters.html.qtpl:55
		}
//line views/encounters.html.qtpl:55
		qw422016.N().S(`
        `)
//line views/encounters.html.qtpl:56
	}
//line views/encounters.html.qtpl:56
	qw422016.N().S(`
      </select>
    </div>
    <div class="form-group">
      <label for="characters">Characters</label>
      <select multiple class="form-control" name="Characters">
        `)
//line views/encounters.html.qtpl:62
	for _, character := range campaign.Characters {
//line views/encounters.html.qtpl:62
		qw422016.N().S(`
          <option value="`)
//line views/encounters.html.qtpl:63
		qw422016.E().V(character.ID)
//line views/encounters.html.qtpl:63
		qw422016.N().S(`">`)
//line views/encounters.html.qtpl:63
		qw422016.E().S(character.Name)
//line views/encounters.html.qtpl:63
		qw422016.N().S(`</option>
        `)
//line views/encounters.html.qtpl:64
	}
//line views/encounters.html.qtpl:64
	qw422016.N().S(`
      </select>
    </div>
    <input type="hidden" name="ID" value="`)
//line views/encounters.html.qtpl:67
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:67
	qw422016.N().S(`" />
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/encounters.html.qtpl:68
	qw422016.E().S(p.CsrfToken)
//line views/encounters.html.qtpl:68
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
  <form action="encounter/delete" method="POST">
    <input type="hidden" name="ID" value="`)
//line views/encounters.html.qtpl:72
	qw422016.E().V(encounter.ID)
//line views/encounters.html.qtpl:72
	qw422016.N().S(`" />
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/encounters.html.qtpl:73
	qw422016.E().S(p.CsrfToken)
//line views/encounters.html.qtpl:73
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
`)
//line views/encounters.html.qtpl:76
}

//line views/encounters.html.qtpl:76
func WriteEncounterEditor(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/encounters.html.qtpl:76
	StreamEncounterEditor(qw422016, p, campaign, encounter, tilemaps)
//line views/encounters.html.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line views/encounters.html.qtpl:76
}

//line views/encounters.html.qtpl:76
func EncounterEditor(p *BasePage, campaign models.FilledCampaign, encounter models.FilledEncounter, tilemaps []models.FilledTilemap) string {
//line views/encounters.html.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
//line views/encounters.html.qtpl:76
	WriteEncounterEditor(qb422016, p, campaign, encounter, tilemaps)
//line views/encounters.html.qtpl:76
	qs422016 := string(qb422016.B)
//line views/encounters.html.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
//line views/encounters.html.qtpl:76
	return qs422016
//line views/encounters.html.qtpl:76
}

//line views/encounters.html.qtpl:78
func StreamEncounterCreator(qw422016 *qt422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:78
	qw422016.N().S(`
  <form action="/encounter/create" method="POST">
    <div class="form-group">
      <label for="name">Name</label>
      <input class="form-control" name="Name" placeholder="Name" />
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" name="Description"></textarea>
    </div>
    <div class="form-group">
      <label for="tilemap">Tilemap</label>
      <select class="form-control" name="TilemapID">
        `)
//line views/encounters.html.qtpl:91
	for _, tilemap := range tilemaps {
//line views/encounters.html.qtpl:91
		qw422016.N().S(`
          <option value="`)
//line views/encounters.html.qtpl:92
		qw422016.E().V(tilemap.ID)
//line views/encounters.html.qtpl:92
		qw422016.N().S(`">`)
//line views/encounters.html.qtpl:92
		qw422016.E().S(tilemap.Name)
//line views/encounters.html.qtpl:92
		qw422016.N().S(`</option>
        `)
//line views/encounters.html.qtpl:93
	}
//line views/encounters.html.qtpl:93
	qw422016.N().S(`
      </select>
    </div>
    <input type="hidden" name="CampaignID" value="`)
//line views/encounters.html.qtpl:96
	qw422016.E().V(campaign.ID)
//line views/encounters.html.qtpl:96
	qw422016.N().S(`" />
    <input type="hidden" name="gorilla.csrf.Token" value="`)
//line views/encounters.html.qtpl:97
	qw422016.E().S(p.CsrfToken)
//line views/encounters.html.qtpl:97
	qw422016.N().S(`" />
    <button type="submit" class="btn btn-primary">Add Encounter</button>
  </form>
`)
//line views/encounters.html.qtpl:100
}

//line views/encounters.html.qtpl:100
func WriteEncounterCreator(qq422016 qtio422016.Writer, p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) {
//line views/encounters.html.qtpl:100
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/encounters.html.qtpl:100
	StreamEncounterCreator(qw422016, p, campaign, tilemaps)
//line views/encounters.html.qtpl:100
	qt422016.ReleaseWriter(qw422016)
//line views/encounters.html.qtpl:100
}

//line views/encounters.html.qtpl:100
func EncounterCreator(p *BasePage, campaign models.FilledCampaign, tilemaps []models.FilledTilemap) string {
//line views/encounters.html.qtpl:100
	qb422016 := qt422016.AcquireByteBuffer()
//line views/encounters.html.qtpl:100
	WriteEncounterCreator(qb422016, p, campaign, tilemaps)
//line views/encounters.html.qtpl:100
	qs422016 := string(qb422016.B)
//line views/encounters.html.qtpl:100
	qt422016.ReleaseByteBuffer(qb422016)
//line views/encounters.html.qtpl:100
	return qs422016
//line views/encounters.html.qtpl:100
}
