// Code generated by qtc from "user_profile.html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/user_profile.html.qtpl:1
package views

//line views/user_profile.html.qtpl:1
import (
	"github.com/etherealmachine/rpg.ai/server/models"
	"github.com/nleeper/goment"
)

//line views/user_profile.html.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/user_profile.html.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/user_profile.html.qtpl:7
type UserProfilePage struct {
	*BasePage
	Campaigns        []models.FilledCampaign
	Characters       []models.Character
	UserSpritesheets []models.Spritesheet
	UserTilemaps     []models.FilledTilemap
}

//line views/user_profile.html.qtpl:16
func StreamUploadAssetComponent(qw422016 *qt422016.Writer) {
//line views/user_profile.html.qtpl:16
	qw422016.N().S(`
<form action="/upload" enctype="multipart/form-data">
  <input type="file" id="fileupload" name="filename[]" multiple>
  <input type="submit" value="Upload">
</form>
`)
//line views/user_profile.html.qtpl:21
}

//line views/user_profile.html.qtpl:21
func WriteUploadAssetComponent(qq422016 qtio422016.Writer) {
//line views/user_profile.html.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/user_profile.html.qtpl:21
	StreamUploadAssetComponent(qw422016)
//line views/user_profile.html.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line views/user_profile.html.qtpl:21
}

//line views/user_profile.html.qtpl:21
func UploadAssetComponent() string {
//line views/user_profile.html.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line views/user_profile.html.qtpl:21
	WriteUploadAssetComponent(qb422016)
//line views/user_profile.html.qtpl:21
	qs422016 := string(qb422016.B)
//line views/user_profile.html.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line views/user_profile.html.qtpl:21
	return qs422016
//line views/user_profile.html.qtpl:21
}

//line views/user_profile.html.qtpl:23
func (p *UserProfilePage) StreamContent(qw422016 *qt422016.Writer) {
//line views/user_profile.html.qtpl:23
	qw422016.N().S(`
  <div class="container">

    `)
//line views/user_profile.html.qtpl:26
	if g, err := goment.New(p.User.CreatedAt); err == nil {
//line views/user_profile.html.qtpl:26
		qw422016.N().S(`
      <p class="my-4">`)
//line views/user_profile.html.qtpl:27
		qw422016.E().S(p.User.Email)
//line views/user_profile.html.qtpl:27
		qw422016.N().S(`, a member since `)
//line views/user_profile.html.qtpl:27
		qw422016.E().S(g.FromNow())
//line views/user_profile.html.qtpl:27
		qw422016.N().S(`</p>
    `)
//line views/user_profile.html.qtpl:28
	}
//line views/user_profile.html.qtpl:28
	qw422016.N().S(`

    <h4>Campaigns</h4>
    <div class="CampaignManager" data-props="`)
//line views/user_profile.html.qtpl:31
	qw422016.E().Q(JSON(map[string]interface{}{
		"Campaigns":  p.Campaigns,
		"Characters": p.Characters,
		"Tilemaps":   p.UserTilemaps,
	}))
//line views/user_profile.html.qtpl:36
	qw422016.N().S(`"></div>

    <h4>Characters</h4>
    <div class="CharacterManager" data-props="`)
//line views/user_profile.html.qtpl:39
	qw422016.E().Q(JSON(map[string]interface{}{
		"Characters": p.Characters,
	}))
//line views/user_profile.html.qtpl:42
	qw422016.N().S(`"></div>

    <h4>Assets</h4>
    <div class="AssetManager" data-props="`)
//line views/user_profile.html.qtpl:45
	qw422016.E().Q(JSON(map[string]interface{}{
		"Spritesheets": p.UserSpritesheets,
		"Tilemaps":     p.UserTilemaps,
	}))
//line views/user_profile.html.qtpl:49
	qw422016.N().S(`"></div>
    <div class="AssetUploader"></div>

  </div>
`)
//line views/user_profile.html.qtpl:53
}

//line views/user_profile.html.qtpl:53
func (p *UserProfilePage) WriteContent(qq422016 qtio422016.Writer) {
//line views/user_profile.html.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/user_profile.html.qtpl:53
	p.StreamContent(qw422016)
//line views/user_profile.html.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line views/user_profile.html.qtpl:53
}

//line views/user_profile.html.qtpl:53
func (p *UserProfilePage) Content() string {
//line views/user_profile.html.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/user_profile.html.qtpl:53
	p.WriteContent(qb422016)
//line views/user_profile.html.qtpl:53
	qs422016 := string(qb422016.B)
//line views/user_profile.html.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/user_profile.html.qtpl:53
	return qs422016
//line views/user_profile.html.qtpl:53
}
