// Code generated by qtc from "jsonrpcservice_template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line jsonrpcservice_template.qtpl:1
package main

//line jsonrpcservice_template.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line jsonrpcservice_template.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line jsonrpcservice_template.qtpl:3
func StreamInterface(qw422016 *qt422016.Writer, def *StructDef) {
//line jsonrpcservice_template.qtpl:3
	qw422016.N().S(`
export interface `)
//line jsonrpcservice_template.qtpl:4
	qw422016.E().S(def.Name)
//line jsonrpcservice_template.qtpl:4
	qw422016.N().S(` {
`)
//line jsonrpcservice_template.qtpl:5
	for _, field := range def.Fields {
//line jsonrpcservice_template.qtpl:5
		qw422016.N().S(`  `)
//line jsonrpcservice_template.qtpl:6
		qw422016.E().S(field.Name)
//line jsonrpcservice_template.qtpl:6
		qw422016.N().S(`: `)
//line jsonrpcservice_template.qtpl:6
		qw422016.E().S(field.Type)
//line jsonrpcservice_template.qtpl:6
		qw422016.N().S(`
`)
//line jsonrpcservice_template.qtpl:7
	}
//line jsonrpcservice_template.qtpl:7
	qw422016.N().S(`}
`)
//line jsonrpcservice_template.qtpl:9
}

//line jsonrpcservice_template.qtpl:9
func WriteInterface(qq422016 qtio422016.Writer, def *StructDef) {
//line jsonrpcservice_template.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jsonrpcservice_template.qtpl:9
	StreamInterface(qw422016, def)
//line jsonrpcservice_template.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line jsonrpcservice_template.qtpl:9
}

//line jsonrpcservice_template.qtpl:9
func Interface(def *StructDef) string {
//line jsonrpcservice_template.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line jsonrpcservice_template.qtpl:9
	WriteInterface(qb422016, def)
//line jsonrpcservice_template.qtpl:9
	qs422016 := string(qb422016.B)
//line jsonrpcservice_template.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line jsonrpcservice_template.qtpl:9
	return qs422016
//line jsonrpcservice_template.qtpl:9
}

//line jsonrpcservice_template.qtpl:11
func StreamJSONRPCService(qw422016 *qt422016.Writer, service *Service) {
//line jsonrpcservice_template.qtpl:11
	qw422016.N().S(`
import JSONRPCService from './JSONRPCService';
`)
//line jsonrpcservice_template.qtpl:13
	for _, method := range service.Methods {
//line jsonrpcservice_template.qtpl:14
		StreamInterface(qw422016, method.RequestDef)
//line jsonrpcservice_template.qtpl:15
		StreamInterface(qw422016, method.ResponseDef)
//line jsonrpcservice_template.qtpl:16
	}
//line jsonrpcservice_template.qtpl:17
	for _, structDef := range service.OtherStructs {
//line jsonrpcservice_template.qtpl:18
		StreamInterface(qw422016, structDef)
//line jsonrpcservice_template.qtpl:19
	}
//line jsonrpcservice_template.qtpl:19
	qw422016.N().S(`
class `)
//line jsonrpcservice_template.qtpl:21
	qw422016.E().S(service.Name)
//line jsonrpcservice_template.qtpl:21
	qw422016.N().S(` extends JSONRPCService {
`)
//line jsonrpcservice_template.qtpl:22
	for _, method := range service.Methods {
//line jsonrpcservice_template.qtpl:22
		qw422016.N().S(`    async `)
//line jsonrpcservice_template.qtpl:23
		qw422016.E().S(method.Name)
//line jsonrpcservice_template.qtpl:23
		qw422016.N().S(`(args: `)
//line jsonrpcservice_template.qtpl:23
		qw422016.E().S(method.RequestDef.Name)
//line jsonrpcservice_template.qtpl:23
		qw422016.N().S(`): Promise<`)
//line jsonrpcservice_template.qtpl:23
		qw422016.E().S(method.ResponseDef.Name)
//line jsonrpcservice_template.qtpl:23
		qw422016.N().S(`> {
      return this.jsonrpc<`)
//line jsonrpcservice_template.qtpl:24
		qw422016.E().S(method.ResponseDef.Name)
//line jsonrpcservice_template.qtpl:24
		qw422016.N().S(`>("`)
//line jsonrpcservice_template.qtpl:24
		qw422016.E().S(method.Name)
//line jsonrpcservice_template.qtpl:24
		qw422016.N().S(`", args);
    }
`)
//line jsonrpcservice_template.qtpl:26
	}
//line jsonrpcservice_template.qtpl:26
	qw422016.N().S(`}

const service = new `)
//line jsonrpcservice_template.qtpl:29
	qw422016.E().S(service.Name)
//line jsonrpcservice_template.qtpl:29
	qw422016.N().S(`("`)
//line jsonrpcservice_template.qtpl:29
	qw422016.E().S(service.Name)
//line jsonrpcservice_template.qtpl:29
	qw422016.N().S(`");
(window as any).`)
//line jsonrpcservice_template.qtpl:30
	qw422016.E().S(service.Name)
//line jsonrpcservice_template.qtpl:30
	qw422016.N().S(` = service;
export default service;
`)
//line jsonrpcservice_template.qtpl:32
}

//line jsonrpcservice_template.qtpl:32
func WriteJSONRPCService(qq422016 qtio422016.Writer, service *Service) {
//line jsonrpcservice_template.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jsonrpcservice_template.qtpl:32
	StreamJSONRPCService(qw422016, service)
//line jsonrpcservice_template.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line jsonrpcservice_template.qtpl:32
}

//line jsonrpcservice_template.qtpl:32
func JSONRPCService(service *Service) string {
//line jsonrpcservice_template.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line jsonrpcservice_template.qtpl:32
	WriteJSONRPCService(qb422016, service)
//line jsonrpcservice_template.qtpl:32
	qs422016 := string(qb422016.B)
//line jsonrpcservice_template.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line jsonrpcservice_template.qtpl:32
	return qs422016
//line jsonrpcservice_template.qtpl:32
}
