// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID          int32     `json:"id"`
	OwnerID     int32     `json:"owner_id"`
	ContentType string    `json:"content_type"`
	Filename    string    `json:"filename"`
	Filedata    []byte    `json:"filedata"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Admin     sql.NullBool `json:"admin"`
	CreatedAt time.Time    `json:"created_at"`
	LastLogin sql.NullTime `json:"last_login"`
}
