// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Spritesheet struct {
	ID         int32
	OwnerID    int32
	Name       string
	Definition json.RawMessage
	Image      []byte
	CreatedAt  time.Time
}

type Tilemap struct {
	ID         int32
	OwnerID    int32
	Name       string
	Definition json.RawMessage
	CreatedAt  time.Time
}

type TilemapReference struct {
	ID            int32
	TilemapID     int32
	SpritesheetID int32
}

type User struct {
	ID        int32
	Email     string
	Admin     sql.NullBool
	CreatedAt time.Time
	LastLogin sql.NullTime
}
