// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Campaign struct {
	ID          int32
	OwnerID     int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type CampaignCharacter struct {
	ID          int32
	CampaignID  int32
	CharacterID int32
}

type Character struct {
	ID         int32
	OwnerID    int32
	Name       string
	Definition json.RawMessage
	Sprite     []byte
	CreatedAt  time.Time
}

type Encounter struct {
	ID          int32
	CampaignID  int32
	Name        string
	Description sql.NullString
	TilemapID   sql.NullInt32
	Events      []json.RawMessage
	CreatedAt   time.Time
}

type Spritesheet struct {
	ID          int32
	OwnerID     int32
	Name        string
	Description sql.NullString
	Definition  json.RawMessage
	Image       []byte
	Hash        []byte
	CreatedAt   time.Time
}

type Thumbnail struct {
	ID            int32
	TilemapID     sql.NullInt32
	SpritesheetID sql.NullInt32
	Image         []byte
	Hash          []byte
	ContentType   string
	Width         int32
	Height        int32
	CreatedAt     time.Time
}

type Tilemap struct {
	ID          int32
	OwnerID     int32
	Name        string
	Description sql.NullString
	Definition  json.RawMessage
	Hash        []byte
	CreatedAt   time.Time
}

type TilemapReference struct {
	ID            int32
	TilemapID     int32
	SpritesheetID int32
}

type User struct {
	ID        int32
	Email     string
	Admin     sql.NullBool
	CreatedAt time.Time
	LastLogin sql.NullTime
}
