// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package models

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, admin, created_at, last_login FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Admin,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}
